---
- hosts: localhost
  tasks:
  - name: add neo4j apt repo
    shell: "{{ item }}"
    with_items:
    - wget --no-check-certificate -O - https://debian.neo4j.org/neotechnology.gpg.key | apt-key add -
    - echo 'deb http://debian.neo4j.org/repo stable/' | tee /etc/apt/sources.list.d/neo4j.list
    - apt-get clean
    - apt-get -o Acquire::CompressionTypes::Order=bz2 update

  - name: install apt packages
    apt:
      name: "{{ item }}"
    with_items:
    - neo4j=1:3.3.3
    - curl
    - vim
    become_method: sudo
    become_user: root
    become: true
