---
- hosts: localhost


  tasks:

  - name: create opt dir
    file: path=/opt state=directory

  - name: get storm
    unarchive:
      src=/src/storm/apache-storm-1.1.0/apache-storm-1.1.0.tar.gz
      dest=/opt
      remote_src=yes
      owner=root
      group=root

  - name: create storm link
    file: src=/opt/apache-storm-1.1.0 dest=/opt/storm state=link owner=root group=root
