---
- hosts: localhost


  tasks:

  - name: create zookeeper dir
    file: path=/opt state=directory

  - name: create data dir
    file: path=/var/zookeeper state=directory owner=root group=root mode=755

  - name: get zookeeper
    unarchive:
      src=/src/zookeeper/zookeeper-3.4.9.tar.gz
      dest=/opt
      remote_src=yes
      owner=root
      group=root

  - name: create zookeeper link
    file: src=/opt/zookeeper-3.4.9 dest=/opt/zookeeper state=link owner=root group=root

  - name: create log dir
    file: path=/var/log/zookeeper state=directory owner=root group=root mode=777
