zookeeper:
  host: zookeeper.pendev
  port: 2181

# TODO: kafka url should be fetched from zookeeper.
kafka:
  host: kafka.pendev
  port: 9092

logging.level.root: DEBUG

ops.heartbeat:
  listener:
    group.id: kilda.heartbeat.listener
    commit.interval: 1000
    sleep: !!java.lang.Long 5000
  acks: all
  retries: 3
  batch.size: 10000
  linger.ms: !!java.lang.Long 1
  buffer.memory.ms: !!java.lang.Long 10000000
  sleep: !!java.lang.Long 5000
  topic: kilda.heartbeat